[theme]
primaryColor = "#3670A1"        # A dark blue for headers and primary elements
backgroundColor = "#F5F7FA"     # Light gray for the main background
secondaryBackgroundColor = "#FFFFFF"  # White for the sidebar background
textColor = "#000000"           # Black text color for readability
font = "sans serif"             # Sans serif font for clean look
